services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ufcanewsletter:latest
    container_name: ufcanewsletter-web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*