# Generated by Django 6.0.7 on 2026-07-08 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curso',
            field=models.CharField(blank=True, choices=[('administracao', 'Administração'), ('agronomia', 'Agronomia'), ('arquitetura_e_urbanismo', 'Arquitetura e Urbanismo'), ('biomedicina', 'Biomedicina'), ('ciencia_da_computacao', 'Ciência da Computação'), ('ciencias_biologicas', 'Ciências Biológicas'), ('ciencias_economicas', 'Ciências Econômicas'), ('design', 'Design'), ('direito', 'Direito'), ('educacao_fisica', 'Educação Física'), ('enfermagem', 'Enfermagem'), ('engenharia_civil', 'Engenharia Civil'), ('engenharia_de_producao', 'Engenharia de Produção'), ('engenharia_de_software', 'Engenharia de Software'), ('engenharia_mecanica', 'Engenharia Mecânica'), ('estatistica', 'Estatística'), ('farmacia', 'Farmácia'), ('fisica', 'Física'), ('fisioterapia', 'Fisioterapia'), ('geografia', 'Geografia'), ('historia', 'História'), ('letras', 'Letras'), ('matematica', 'Matemática'), ('medicina', 'Medicina'), ('medicina_veterinaria', 'Medicina Veterinária'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('pedagogia', 'Pedagogia'), ('psicologia', 'Psicologia'), ('quimica', 'Química'), ('servico_social', 'Serviço Social'), ('sistemas_de_informacao', 'Sistemas de Informação'), ('zootecnia', 'Zootecnia')], max_length=150),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='periodo',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
