# Generated by Django 6.0.7 on 2026-07-09 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_perfil_curso_alter_perfil_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='cursos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('administracao', 'Administração'), ('agronomia', 'Agronomia'), ('arquitetura_e_urbanismo', 'Arquitetura e Urbanismo'), ('biomedicina', 'Biomedicina'), ('ciencia_da_computacao', 'Ciência da Computação'), ('ciencias_biologicas', 'Ciências Biológicas'), ('ciencias_economicas', 'Ciências Econômicas'), ('design', 'Design'), ('direito', 'Direito'), ('educacao_fisica', 'Educação Física'), ('enfermagem', 'Enfermagem'), ('engenharia_civil', 'Engenharia Civil'), ('engenharia_de_producao', 'Engenharia de Produção'), ('engenharia_de_software', 'Engenharia de Software'), ('engenharia_mecanica', 'Engenharia Mecânica'), ('estatistica', 'Estatística'), ('farmacia', 'Farmácia'), ('fisica', 'Física'), ('fisioterapia', 'Fisioterapia'), ('geografia', 'Geografia'), ('historia', 'História'), ('letras', 'Letras'), ('matematica', 'Matemática'), ('medicina', 'Medicina'), ('medicina_veterinaria', 'Medicina Veterinária'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('pedagogia', 'Pedagogia'), ('psicologia', 'Psicologia'), ('quimica', 'Química'), ('servico_social', 'Serviço Social'), ('sistemas_de_informacao', 'Sistemas de Informação'), ('zootecnia', 'Zootecnia')], max_length=150), blank=True, default=list, help_text='Cursos aos quais o conteúdo é direcionado. Vazio = nenhum curso específico.'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='interesses',
            field=models.ManyToManyField(blank=True, help_text='Interesses aos quais o conteúdo é direcionado.', related_name='conteudos', to='newsletter.interesse'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='universal',
            field=models.BooleanField(default=False, help_text='Se marcado, o conteúdo aparece no feed de todos os perfis (ex.: avisos institucionais), ignorando curso e interesses.'),
        ),
    ]
