# Generated by Django 6.0.7 on 2026-07-29 18:30

import django.db.models.deletion
from django.db import migrations, models


def _aprovar_conteudos_existentes(apps, schema_editor):
    """Preserva o comportamento anterior: sem fila de moderação, tudo era visível.

    O campo `status` nasce com default `pendente` (para o que o coletor da #16 e
    o classificador da #17 criarem a partir de agora), mas os `Conteudo` que já
    existiam antes desta migração não passaram por nenhuma revisão — marcá-los
    como `pendente` os removeria do feed. Migram como `aprovado`, sem sumir.
    """
    Conteudo = apps.get_model('newsletter', 'Conteudo')
    Conteudo.objects.update(status='aprovado')


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_conteudo_cursos_conteudo_interesses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='gerado_por_ia',
            field=models.BooleanField(default=False, help_text='Indica se o resumo foi gerado por IA (transparência exigida por #18).'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='prazo',
            field=models.DateTimeField(blank=True, help_text='Data-limite extraída do conteúdo (ex.: prazo de inscrição), quando houver.', null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='publico_alvo',
            field=models.CharField(blank=True, default='', help_text="Público-alvo extraído do conteúdo na sumarização (ex.: 'discentes de graduação').", max_length=255),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('descartado', 'Descartado')], default='pendente', help_text='Só conteúdo aprovado aparece no feed dos estudantes.', max_length=20),
        ),
        migrations.RunPython(_aprovar_conteudos_existentes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='conteudo',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link do conteúdo original na fonte (ex.: página do edital).'),
        ),
        migrations.AddField(
            model_name='fonte',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Fontes inativas são ignoradas pelo coletor (US-03.1, issue #16).'),
        ),
        migrations.AddField(
            model_name='fonte',
            name='ultima_coleta',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última coleta bem-sucedida. O scheduler compara com `intervalo_coleta` para decidir se já é hora de coletar de novo.', null=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Nulo enquanto o conteúdo não é classificado (US-03.2, issue #17).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteudos', to='newsletter.categoria'),
        ),
    ]
