# Generated by Django 6.0.8 on 2026-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_campos_coleta_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='tipo',
            field=models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('calendario', 'Calendário'), ('concurso', 'Concursos e Seleções')], max_length=20),
        ),
    ]
