# Generated by Django 6.0.8 on 2026-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_tipo_fonte_concurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='anexos',
            field=models.JSONField(blank=True, default=list, help_text='Anexos PDF processados (issue #54). Cada item: url, file_hash, text, metadata, edital_number, edital_year, is_rectification.'),
        ),
    ]
