# Generated by Django 6.0.8 on 2026-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_perfil_push_ativo_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link do conteúdo original na fonte (ex.: página do edital).', max_length=500),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
